// SPDX-License-Identifier: GPL-2.0-only
/* Airoha EN75xx parallel NAND identification table. */

#include <stdint.h>
#include <string.h>

#include <ecnt_spi_nand_flash.h>

#define PNAND_ID(_mfr, _dev, _name, _size, _page, _erase, _oob, _feature, \
		  _ext, _timing, _required_ecc, _cycles, _controller_ecc) { \
	.mfr_id = (_mfr), \
	.dev_id = (_dev), \
	.ptr_name = (const uint8_t *)(_name), \
	.device_size = (_size), \
	.page_size = (_page), \
	.erase_size = (_erase), \
	.oob_size = (_oob), \
	.oob_free_layout = &ooblayout_spi_controller_ecc, \
	.feature = (_feature), \
	.ext_id = (_ext), \
	.timing_setting = (_timing), \
	.min_ecc_req = (_required_ecc), \
	.addr_cycle = (_cycles), \
	.soc_ecc_ability = (_controller_ecc), \
}

static const struct SPI_NAND_FLASH_INFO_T parallel_nand_flash_table[] = {
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_MXIC, 0xf1, "MX30LF1G18AC",
		  _SPI_NAND_CHIP_SIZE_1GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x029580, PARALLEL_NAND_FLASH_TIMING, 4, 4, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_MXIC, 0xda, "MX30LF2G18AC",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x069590, PARALLEL_NAND_FLASH_TIMING, 4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_MXIC, 0xf1, "MX30LF1G08AA",
		  _SPI_NAND_CHIP_SIZE_1GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0xc21d80,
		  PARALLEL_NAND_FLASH_TIMING, 1, 4, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_ESMT, 0xda, "F59L2G81A",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x449590, PARALLEL_NAND_FLASH_TIMING, 4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_ESMT, 0xdc, "F59L4G81A",
		  _SPI_NAND_CHIP_SIZE_4GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x549590, PARALLEL_NAND_FLASH_TIMING, 4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_WINBOND, 0xdc, "W29N08GVSIAD",
		  _SPI_NAND_CHIP_SIZE_8GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  PARALLEL_NAND_FLASH_2CE, 0x549590, PARALLEL_NAND_FLASH_TIMING, 1, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_WINBOND, 0xd3, "W29N08GVSIAA",
		  _SPI_NAND_CHIP_SIZE_8GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x589591, PARALLEL_NAND_FLASH_TIMING, 1, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_WINBOND, 0xda, "W29N02KVSIAF",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_128BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x069510, PARALLEL_NAND_FLASH_TIMING, 4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_WINBOND, 0xda, "W29N02KVSIAE",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_128BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x079510, PARALLEL_NAND_FLASH_TIMING, 8, 5, 8),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_WINBOND, 0xda, "W29N02GV",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x049590, PARALLEL_NAND_FLASH_TIMING,
		  1, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_SKYHIGH, 0xda,
		  "S34ML02G300TFI00", _SPI_NAND_CHIP_SIZE_2GBIT,
		  _SPI_NAND_PAGE_SIZE_2KBYTE, _SPI_NAND_BLOCK_SIZE_128KBYTE,
		  _SPI_NAND_OOB_SIZE_128BYTE, SPI_NAND_FLASH_FEATURE_NONE,
		  0x469500, 0x44333, 1, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_SKYHIGH, 0xf1, "S34ML01G1",
		  _SPI_NAND_CHIP_SIZE_1GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x1d00, PARALLEL_NAND_FLASH_TIMING,
		  1, 4, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_SKYHIGH, 0xda, "S34ML02G1",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x449590, PARALLEL_NAND_FLASH_TIMING,
		  1, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_SKYHIGH, 0xdc, "S34ML04G1",
		  _SPI_NAND_CHIP_SIZE_4GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x549590, PARALLEL_NAND_FLASH_TIMING,
		  1, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_SKYHIGH, 0xda, "S34ML02G2",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_128BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x469590, PARALLEL_NAND_FLASH_TIMING,
		  4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_SKYHIGH, 0xda, "S34ML02G2 (alt ID)",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_128BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x909546, PARALLEL_NAND_FLASH_TIMING,
		  4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_MICRON, 0xf1, "MT29F01G08ABAEA",
		  _SPI_NAND_CHIP_SIZE_1GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_64BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x049580, PARALLEL_NAND_FLASH_TIMING, 4, 5, 4),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_MICRON, 0xda, "MT29F02G08ABAGA",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_128BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x069590, PARALLEL_NAND_FLASH_TIMING, 8, 5, 12),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_MICRON, 0xd3, "MT29F08G08ABACA",
		  _SPI_NAND_CHIP_SIZE_8GBIT, _SPI_NAND_PAGE_SIZE_4KBYTE,
		  _SPI_NAND_BLOCK_SIZE_256KBYTE, 0xe0,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x64a690, PARALLEL_NAND_FLASH_TIMING, 8, 5, 12),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_TOSHIBA, 0xd3, "TC58NVG4S0HTA20",
		  _SPI_NAND_CHIP_SIZE_16GBIT, _SPI_NAND_PAGE_SIZE_4KBYTE,
		  _SPI_NAND_BLOCK_SIZE_256KBYTE, _SPI_NAND_OOB_SIZE_256BYTE,
		  PARALLEL_NAND_FLASH_2CE, 0x762691, PARALLEL_NAND_FLASH_TIMING, 8, 5, 12),
	PNAND_ID(_SPI_NAND_MANUFACTURER_ID_TOSHIBA, 0xda, "TC58NVG1S3HTAI0",
		  _SPI_NAND_CHIP_SIZE_2GBIT, _SPI_NAND_PAGE_SIZE_2KBYTE,
		  _SPI_NAND_BLOCK_SIZE_128KBYTE, _SPI_NAND_OOB_SIZE_128BYTE,
		  SPI_NAND_FLASH_FEATURE_NONE, 0x761590, PARALLEL_NAND_FLASH_TIMING, 8, 5, 8),
};

SPI_NAND_FLASH_RTN_T
parallel_nand_scan_flash_table(struct SPI_NAND_FLASH_INFO_T *result)
{
	unsigned int i;

	for (i = 0; i < sizeof(parallel_nand_flash_table) /
			    sizeof(parallel_nand_flash_table[0]); i++) {
		const struct SPI_NAND_FLASH_INFO_T *entry =
			&parallel_nand_flash_table[i];

		/* Extended ID selects the exact geometry among devices sharing two bytes. */
		if (result->mfr_id == entry->mfr_id &&
		    result->dev_id == entry->dev_id &&
		    result->ext_id == entry->ext_id) {
			memcpy(result, entry, sizeof(*result));
			return SPI_NAND_FLASH_RTN_NO_ERROR;
		}
	}

	return SPI_NAND_FLASH_RTN_PROBE_ERROR;
}
